### ISSUE TITLE
Maven dependcy not found

### ISSUE THREAD

**Issue by frankred** [rrice/java-string-similarity#3]
Hi just included it to my pom.xml but Intellij did not found it :( Is there something I looked over?

```
        <dependency>
            <groupId>net.ricecode</groupId>
            <artifactId>string-similarity</artifactId>
            <version>1.0.0</version>
        </dependency>
```

**Comment by mchmielarz** [comment]
Did you install the project in your local repository? Check **Installation** part from README.md. Artifacts of the project aren't published in Maven Central.

**Comment by rrice** [comment]
That is correct. This project does not publish to Maven Central because the project is not fully compliant with the [publishing requirements](http://central.sonatype.org/pages/requirements.html). I normally publish this project on a private server, so the project that need.  However, if there is enough demand, I would not object to polish up the project to meet these requirements.

**Comment by frankred** [comment]
Ahhh now I get it. Sorry for my question im mostly new to maven and java. Thank you for the quick reply and btw: Nice project! I use it for this https://github.com/frankred/jSona  and working to switch to maven. Good times.

**Comment by renatorroliveira** [comment]
Hi there,
@rrice i would like to help publishing this library on maven central.
I already published some libs on central and could help to do this with that one.
Are you interested in doing this? I want to use this library but without availability in the central i can't, due to company's internal limitations.

**Comment by rrice** [comment]
@renatorroliveira Absolutely. I am starting to some work now to meet the requirements outlined [here](http://central.sonatype.org/pages/ossrh-guide.html).  I could use some help with getting the pom files set up correctly.  So, I will accept pull request that helps achieve this goal. Thanks!

**Comment by renatorroliveira** [comment]
Great!
I will setup the POM for this purpose.
@rrice While i do this, i suggest you open a ticket on Sonatype JIRA to create the projects/repositories for your groupId:
http://central.sonatype.org/pages/ossrh-guide.html#create-a-ticket-with-sonatype

**Comment by rrice** [comment]
The JIRA ticket is filed under [OSSRH-19996](https://issues.sonatype.org/browse/OSSRH-19996)

**Comment by renatorroliveira** [comment]
Great, it is already created. I will proceed with the POM.

**Comment by renatorroliveira** [comment]
@rrice Can you contact me via e-mail? You will need to prepare your environment to release versions of the library to the central, and that include generating GPG key pairs and others confidential stuff.

**Comment by rrice** [comment]
@renatorroliveira I have already created and updated my GPG key pairs. I will contact you soon to discuss any publishing requirements that I have missed.  Thanks!

**Comment by renatorroliveira** [comment]
Hi @rrice,
Very good! So i will post here some guidelines regarding my pull request (#6) to ease the publishing process.

In my published libraries, i configure the GPG and Sonatype repositories in the Maven's settings.xml (`~/.m2/settings.xml`). Below is an example configuration where you have to put the information of your  GPG key and Sonatype OSS account:

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository/>
  <interactiveMode/>
  <usePluginRegistry/>
  <offline/>
  <pluginGroups/>
  <servers>
    <server>
      <id>ossrh</id>
      <username>YOUR_SONATYPE_USERNAME</username>
      <password>YOUR_SONATYPE_PASSWORD</password>
    </server>
  </servers>
  <mirrors/>
  <proxies/>
  <profiles>
    <profile>
      <id>ossrh</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <gpg.executable>gpg2</gpg.executable>
	<gpg.keyname>E994461B</gpg.keyname>
        <gpg.passphrase>YOUR_KEY_PASSPHRASE</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
  <activeProfiles/>
</settings>
```

You can get the `gpg.keyname` property listing your keys with the `gpg` program.

With that configured, i usually use the Maven Release Plugin to deploy the artifacts to the repositories. In the POM i configured to sign the artifacts when you activate the `release` profile, so to deploy the artifacts you can execute:

```shell
mvn release:prepare -P release
mvn release:perform -P release
```

If the process goes well, then a staging repository will be created at Sonatype OSS (http://oss.sonatype.org/). You have to close the staging repository and if it succeeds, you can release it. After releasing, in about 15 minutes the artifacts will be available at Maven Central Repository (http://central.maven.org/maven2/net/ricecode/).

If you have any problems just contact me =)

**Comment by rrice** [comment]
Looks like the component is published to central:

http://repo1.maven.org/maven2/net/ricecode/string-similarity/1.0.0/

Thank you @renatorroliveira for your assistance.

**Comment by renatorroliveira** [comment]
@rrice Awesome news!
Now we can just add the dependency in the POM =D

**Comment by frankred** [comment]
AWESOME! THX!
